# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.15.0
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: Both
odoo_version: 15.0
org_name: Christopher Ormaza
org_slug: cormaza
rebel_module_groups: []
repo_description: Misc Tools for Odoo
repo_name: Misc Tools for Odoo
repo_slug: odoo-addons
repo_website: https://github.com/cormaza/odoo-addons

