# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.19.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: Both
odoo_version: 16.0
org_name: Christopher Ormaza
org_slug: cormaza
rebel_module_groups: []
repo_description: Some tools for odoo 16
repo_name: Various Tools for Odoo 16
repo_slug: odoo-addons
repo_website: https://github.com/cormaza/odoo-addons
use_pyproject_toml: false
use_ruff: true

