# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.2
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: Christopher Ormaza
org_slug: cormaza
rebel_module_groups: []
repo_description: 'TODO: add repo description.'
repo_name: bank-payment
repo_slug: bank-payment
repo_website: https://github.com/cormaza/odoo-addons
travis_apt_packages: []
travis_apt_sources: []
