{
    "name": "UTM Chatter",
    "version": "13.0.1.0.0",
    "summary": "Add Chatter to UTM Objects",
    "category": "Hidden",
    "author": "Christopher Ormaza",
    "website": "https://github.com/cormaza/odoo-addons",
    "license": "AGPL-3",
    "depends": ["utm", "mail"],
    "data": ["views/utm_views.xml"],
    "installable": True,
    "auto_install": False,
    "maintainers": ["cormaza"],
    "development_status": "Beta",
    "external_dependencies": {"python": []},
}
